version: 2

sources:
  - name: qwt_raw
    database: "{{env_var('DBT_SOURCEDATABASE','qwtanalytics_dev')}}"
    # environment varible whihc help to change value dynamically at run time
    schema: "{{env_var('DBT_SOURCESCHEMA','raw_dev')}}"
    tables:
      - name: customers
      - name: orders
      - name: orderdetails
      - name: products
      - name: employees
      - name: shipments
      - name: suppliers_xml